apiVersion: apps/v1
kind: Deployment
metadata:
  name: usersapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usersapi
  template:
    metadata:
      labels:
        app: usersapi
    spec:
      containers:
        - name: usersapi
          image: automationrepository.azurecr.io/usersapi-image
          ports:
            - containerPort: 8083